services:

  # -------------------------------
  # BLUE APP (Primary)
  # -------------------------------
  app-blue:
    container_name: selfhealing-8080
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_VERSION: "blue-local"
      APP_ENV: "development"
      JAVA_OPTS: "-Xms128m -Xmx256m"
    volumes:
      - app-logs:/var/log/app
    restart: unless-stopped
    networks:
      - selfhealing-net

  # -------------------------------
  # GREEN APP (Secondary)
  # -------------------------------
  app-green:
    container_name: selfhealing-8081
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - app-blue
    ports:
      - "8081:8080"
    environment:
      APP_VERSION: "green-local"
      APP_ENV: "development"
      JAVA_OPTS: "-Xms128m -Xmx256m"
    volumes:
      - app-logs:/var/log/app
    restart: unless-stopped
    networks:
      - selfhealing-net

  # -------------------------------
  # NGINX (Frontend + Proxy)
  # -------------------------------
  nginx:
    container_name: selfhealing-nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro   # 🔥 IMPORTANT FIX
      - ./nginx/html:/usr/share/nginx/html                  # 🔥 frontend here
      - nginx-logs:/var/log/nginx
    depends_on:
      - app-blue
    restart: unless-stopped
    networks:
      - selfhealing-net

# -------------------------------
# VOLUMES
# -------------------------------
volumes:
  app-logs:
  nginx-logs:

# -------------------------------
# NETWORK
# -------------------------------
networks:
  selfhealing-net:
    driver: bridge